name: Run Python Lint (& Tests)
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.5
          cache: 'pipenv'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ secrets.ACCESS_TOKEN }}
          password: x-oauth-basic
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Run lint with black
        uses: psf/black@stable
